let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("jZfZbts4FIZfJXBvW4D7csm1DZppi7oYYFD0QuMoGaG2XCgyBnn7UrYkyz20ZMuJCfzf4XIWkvr+fcWRcvvdr21V1O3q7eoNpYQolVp2eyjTD05/3ffHW8hiLCWlqfW+Kcu6B6+wSjkXQmo9VM//tXd978MAOQvGjNF6tLhhDGMYm1h8LR/neeeEkDK1PjdF/VwuLYAQzlNrsVvvnTt2+0+53e7/v4TNw0PHoOPnLF2q8fiB6nNTbQ7b9tCUpz6I4mGZ0p7LJYpEywYKX8eo1MqzsaeOlCgHGiYCUkujWqE4FUuUC5Lhxb4CUx6bRUqbgPESFaMTHI6Yorwrm83gVu41dNiUcdhGew4jzjFROMMoGMqXT2X9choJEyz0HMEIZ5TMEQJRT2C6TQhpjfWzhNJcZBw8IaxBjsC0nRDRes9mR0mud5nCCI+HTdFW+/rke04MXO8fTEp7AeNzAcXoNcoEKNRl8/za11gQMEOnAGMExu8C0DqzoAkgNIVeOwOaypBzyQh4572HG8EESNWN/AwQY8AcriLer/8ypxzEUsAORp0LQTTM0VH3snuA/uHDulOx4VxzqO535baoH+/W5ebQVO3rEHsFS/MKK5WBfsmyPGiZqaEs61KaO3YjyzChMHj3dVs21b5Znco3YphjFwhTwkH/TRGODKd2FlGWCQIreIo4KRiGgZwiHlOcqeEpEpnUZH66qfRy2/VD8e9JR5waBeMx6tEbkTn8znokisGq+vTZmD41gstsD4NOBI3ynGbjzrBui7bf/7NlPdFFzFTURNdCwvWNuojGexiIUVdEqEy4R12z7pnRjbAU1tGoGyolgzU56g476ub0dMwyeNCOeoo/z5xIEz3IzMb7Ld3UXn7tm3bcw7FmeIgUviDL4uXQDJuG0S7T2RmhWEsP/TVFQvRSwJD+XaasTrO6M09PRdW8HCfFMcp4N4cSRAyHc8uiBGMEayaHSmxkZovKocbimDnBcqglCgkYtByaLsGcwfzMocEGpDOlUNZttUv/7u7rxyod2qfCthyl/XeVuYdfMfC6P/xy1/ErNsRKd7yAn99TFixwNJF2scm8p3wk7+Jxsm8ITb5Gx36Lzc9rlPY6Hu8375vi9RpkLUGU5fyQGFekWTTr4um01zDmpOlX8+5LU+2KBvb7hw3i0uDBxmz6cpszYVwHJgcXJJtNeXwhmrOhVgnqJjY3jEND9/TuuXE5EnXPYHPT1KJTnHR5c3o7hEY/fgM=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Agency = _t, LogoColors = _t, Note = _t, UseAsBorder = _t, UseAsBackground = _t, Transparency = _t]),
    ChangeDataTypes = Table.TransformColumnTypes(Source,{{"Agency", type text}, {"LogoColors", type text}, {"UseAsBorder", Int64.Type}, {"UseAsBackground", Int64.Type}, {"Transparency", Int64.Type}}),
    DuplicateLogoColors = Table.DuplicateColumn(ChangeDataTypes, "LogoColors", "LogoColors - Copy"),
    RenameDupeToHexColor = Table.RenameColumns(DuplicateLogoColors,{{"LogoColors - Copy", "HexColor"}}),
    AlphaSort = Table.Sort(RenameDupeToHexColor,{{"Agency", Order.Ascending}, {"LogoColors", Order.Ascending}}),
    #"Renamed Columns" = Table.RenameColumns(AlphaSort,{{"UseAsBackground", "UseAsBackGround"}})
in
    #"Renamed Columns"