// Fact_RunningTotalQty
let
    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("bZa7jlRBDET/ZWOC7Xc7RCJBxESrDVaCAPEIFvh/0EyjW9RxdlWyy2W73DNPTw9vf//89fry7cvLw5uHqA/Pb/6HGqHaAfXCxAA0G7kYtR6ZOAHFBlRIPxchJm5Cg1yLIhbVB6MKReyEPhnhINcjpxPMHIkKQpu73aQfbLIyaidRbLKwo0h8wqhOqCWLZNSkWScrtqRt0i9ybe62J1CyNHI1QoWJnbpmcrb0xOI6NqNKQp/4K9GViGDFSCydGJ8jLKQvyduROCc5teTeOftIPEFdK4GSJzM5PkKdIga5gg2NZI/kqsmgKWKy7cp5dSZWSu3Jo5A8hsnsGVW52nGHPn64Lvj2fS7w9n2avn0PiTnevMdXweX7/FTcvpdwDuEsomFLfEj82cVdTwiPahC8qH7JDeGfyin4kO+qGqb0KLlLvpvGSF9F+m3C2aRWkbkt+e7S45T5V/n+96N2b0AKVxE0RGiRwlsKFBniEs4peJNmqtYSnibxIfFTzSHatg5UNUxtUjh1qaJh6YLVBFI3tK7q1LpqSqm7BZ9qPulxK7/2rpyirYvmLrWW8IfuV3JDYobUnapHzaRzlpiQmCFz6MLZ1dBa9577/vXzt5cfn67LuoBzFhdQHDiHLBEONJAiYhlwXoQLOG4VpcUB72V52QlSpLiws2ABnPRY+wK2AxMT816WpyxvLlDFJxYOFJfenKN6SvOyBUPGgLy57UMO1zG87MYaMHWPqFD66N2F53SPKL7L4c0sbMq7255SXXtxjo3lwiDOMZ2jecT2iPBNTRgEFsJ9YEDYFNrHCL3KcNIOG8JC3lz15qqnDCwKZX0NzZtrmKmndPgDpnOl4To2lu1AxfFjtx4xXOmA+V3p+f/w7vOP7y+vX6+H7ALOvVzAsdQFdAe2p3Svci75Ao5xL2A40EDqHGdzUsXLnldJevFuj9cF8LLhEcV1DCedLqy5juWk1Tk2hDnpdh3nlZKJ+Uyx/QbprrQ56XKguh2Kl92wg3M051jYrQsLLArzcNJwHd2rhAsLH1CgW+wWBwSvO0dzYdM5igv791MoE4KnvO5EGYwMB4O6eA08ZeBOXcfyiIpb97LbOcJXt1DFB9QxVOcY8LZHFNwpInwNE5cMx+AsPaX5xLpHdLxsTrpQ9u8qn/8A", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Country = _t, Value = _t]),
    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Country", type text}, {"Value", Int64.Type}})
in
    #"Changed Type"
